### ISSUE TITLE
Error when adding body_add_gg()

### ISSUE THREAD

**Issue by guaribr** [davidgohel/officer#302] opened 2020-05-24 18:20 UTC
When I add a ggplot to a document I keep on having this error:

The example: 

```
library(tidyverse)
library(officer)
doc <- read_docx()
gg_plot <- ggplot(data = iris ) + geom_point(mapping = aes(Sepal.Length, Petal.Length))
doc <- body_add_gg(doc, value = gg_plot, style = "centered")
print(doc, target = "my_doc.docx") 
```
 The error:
```
Error in external_img(new_src, width = width, height = height) : 
  src must be a string starting with 'rId' or an image filename
In addition: Warning messages:
1: In grSoftVersion() :
  unable to load shared object '/Library/Frameworks/R.framework/Resources/modules//R_X11.so':
  dlopen(/Library/Frameworks/R.framework/Resources/modules//R_X11.so, 6): Library not loaded: /opt/X11/lib/libSM.6.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/4.0/Resources/modules/R_X11.so
  Reason: image not found
2: In cairoVersion() :
  unable to load shared object '/Library/Frameworks/R.framework/Resources/library/grDevices/libs//cairo.so':
  dlopen(/Library/Frameworks/R.framework/Resources/library/grDevices/libs//cairo.so, 6): Library not loaded: /opt/X11/lib/libXrender.1.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/4.0/Resources/library/grDevices/libs/cairo.so
  Reason: image not found
3: In png(filename = file, width = width, height = height, units = "in",  :
  failed to load cairo DLL
```

sessionInfo():
One note: I had the previous version of R (version 3.6.3) when the error started. I thought that the error had to do with R version so updated it to 4
```
R version 4.0.0 (2020-04-24)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.4

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] pt_PT.UTF-8/pt_PT.UTF-8/pt_PT.UTF-8/C/pt_PT.UTF-8/pt_PT.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] forcats_0.5.0   stringr_1.4.0   dplyr_0.8.5     purrr_0.3.4     readr_1.3.1     tidyr_1.1.0     tibble_3.0.1    ggplot2_3.3.0  
 [9] tidyverse_1.3.0 officer_0.3.11 

loaded via a namespace (and not attached):
 [1] zip_2.0.4        Rcpp_1.0.4.6     cellranger_1.1.0 pillar_1.4.4     compiler_4.0.0   dbplyr_1.4.3     tools_4.0.0     
 [8] digest_0.6.25    uuid_0.1-4       lubridate_1.7.8  jsonlite_1.6.1   lifecycle_0.2.0  nlme_3.1-147     gtable_0.3.0    
[15] lattice_0.20-41  pkgconfig_2.0.3  rlang_0.4.6      reprex_0.3.0     cli_2.0.2        DBI_1.1.0        rstudioapi_0.11 
[22] haven_2.2.0      withr_2.2.0      httr_1.4.1       xml2_1.3.2       fs_1.4.1         generics_0.0.2   vctrs_0.3.0     
[29] hms_0.5.3        grid_4.0.0       tidyselect_1.1.0 glue_1.4.1       R6_2.4.1         fansi_0.4.1      readxl_1.3.1    
[36] farver_2.0.3     modelr_0.1.8     magrittr_1.5     backports_1.1.7  scales_1.1.1     ellipsis_0.3.1   rvest_0.3.5     
[43] assertthat_0.2.1 colorspace_1.4-1 labeling_0.3     stringi_1.4.6    munsell_0.5.0    broom_0.5.6      crayon_1.3.4   
```

Thanks, and sorry for deleting guidelines!

**Comment by davidgohel** [comment] 2020-05-24 18:55
Sorry, I can't help; I am not able to reproduce and the required guidelines to report an issue are missing.

**Comment by guaribr** [comment] 2020-05-24 18:58
Oh, sorry, where are the guidelines?

**Comment by davidgohel** [comment] 2020-05-24 18:59
This is the text you deleted when you opened an issue

**Comment by guaribr** [comment] 2020-05-24 19:00
I got it, thanks and sorry. I am doing it properly. Will be done in a minute.

Bruno Guarita
Em 24/05/2020, 19:59 +0100, David Gohel <notifications@github.com>, escreveu:

**Comment by davidgohel** [comment] 2020-05-24 19:01
You can edit your post, it's not necessary to create a new one.

**Comment by john-harrold** [comment] 2020-05-24 22:01
I tested it under R 3.5.1 and 4.0 and I was unable to reproduce the error. Here is my sessionInfo() for the 4.0 shot:

```
R version 4.0.0 (2020-04-24)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Mojave 10.14.5

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRblas.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] officer_0.3.11  forcats_0.5.0   stringr_1.4.0   dplyr_0.8.5    
 [5] purrr_0.3.4     readr_1.3.1     tidyr_1.1.0     tibble_3.0.1   
 [9] ggplot2_3.3.0   tidyverse_1.3.0

loaded via a namespace (and not attached):
 [1] zip_2.0.4        Rcpp_1.0.4.6     cellranger_1.1.0 pillar_1.4.4    
 [5] compiler_4.0.0   dbplyr_1.4.3     tools_4.0.0      digest_0.6.25   
 [9] uuid_0.1-4       jsonlite_1.6.1   lubridate_1.7.8  lifecycle_0.2.0 
[13] nlme_3.1-147     gtable_0.3.0     lattice_0.20-41  pkgconfig_2.0.3 
[17] rlang_0.4.6      reprex_0.3.0     cli_2.0.2        rstudioapi_0.11 
[21] DBI_1.1.0        haven_2.2.0      withr_2.2.0      xml2_1.3.2      
[25] httr_1.4.1       fs_1.4.1         generics_0.0.2   vctrs_0.3.0     
[29] hms_0.5.3        grid_4.0.0       tidyselect_1.1.0 glue_1.4.1      
[33] R6_2.4.1         fansi_0.4.1      tcltk_4.0.0      readxl_1.3.1    
[37] farver_2.0.3     modelr_0.1.8     magrittr_1.5     backports_1.1.7 
[41] scales_1.1.1     ellipsis_0.3.1   rvest_0.3.5      assertthat_0.2.1
[45] colorspace_1.4-1 labeling_0.3     stringi_1.4.6    munsell_0.5.0   
[49] broom_0.5.6      crayon_1.3.4   
```

**Comment by davidgohel** [comment] 2020-05-25 11:58
thanks @john-harrold !

@guaribr I think you have an issue with your settings:

`failed to load cairo DLL`

The error is because you have an issue with cairo. The code fails here:

```
  options(bitmapType='cairo')
  png(filename = file, width = width, height = height, units = "in", res = res, ...)
  print(value)
  dev.off()
```

I think by running `capabilities()` you will see you have an issue with cairo. I think you don't have X11 installed. Could you make sure X11 is available, if not, could you install https://www.xquartz.org/?

**Comment by guaribr** [comment] 2020-05-25 12:25
Thanks David!… and thanks for your library. It makes reporting much much easier.

Bruno Guarita
Em 25/05/2020, 12:58 +0100, David Gohel <notifications@github.com>, escreveu:

**Comment by davidgohel** [comment] 2020-05-25 16:57
@guaribr sorry, I am not sure I understood, is it solved with X11 installation? If so, I can close the issue

**Comment by guaribr** [comment] 2020-05-25 17:06
Yes, after doing the X11 installation I was able to add body_add_gg() with no problems.
Thanks!

Bruno Guarita
Em 25/05/2020, 17:57 +0100, David Gohel <notifications@github.com>, escreveu:

**Comment by davidgohel** [comment] 2020-05-25 17:09
Cool, thanks

**Comment by davidgohel** [comment] 2020-12-09 15:22
Actually, forcing `cairo` is not a good idea. It should not be a requirement

**Comment by davidgohel** [comment] 2020-12-28 12:07
Required by cran, fixed in dev version

**Closed by davidgohel** 2020-12-28 12:07 UTC
Labels: invalid
