### ISSUE TITLE
Big ggplot to PPTX issue

### ISSUE THREAD

**Issue by luis-zapata-b** [davidgohel/officer#288] opened 2020-03-25 16:28 UTC
Im triying to print a ggplot image to a Pptx with a complex ggplot.

geo = z %>%
    ggplot(aes(x = date, y = hits)) +
    geom_xspline(aes(color = keyword),size=3,spline_shape=0.5)  +
    ggtitle(paste("Servicios: palabras relacionadas a",i,"en Google Trends")) +
    geom_smooth(aes(fill="black"),color="black") +
    geom_vline(aes(xintercept = as.POSIXct("2020-03-15")),size=1.5) +
    geom_vline(aes(xintercept = as.POSIXct("2020-03-6")),size=1.5) +
    xlab("") +
    labs(color = i) +
    theme(plot.margin = unit(c(1,1,2,1), "lines"),
          axis.text.x = element_text(angle = 90, hjust = 1,vjust=0.5)) +
    coord_cartesian(clip="off") +
    scale_fill_identity(name = '', guide = 'legend',labels = c('Tendencia')) +
    scale_x_datetime(breaks = unique(c(seq(min(z$date)+days(1),max(z$date),by="weeks"),as.POSIXct(Sys.Date()-days(1)))),
                     date_labels = ("%b %d"))
  

read_pptx(paste(path2,"Model.pptx",sep="")) %>% 
  add_slide(layout = "En blanco",master = "Tema de Office") %>% #In spanish is like this
  ph_with(value = geo, ph_location_fullsize())

print(diapo,target = paste("GoogleTrends_.pptx",sep=""))

When i try to open the Pptx, windows tells me that is broken and that it will try to repair it. When i tell it to repair it, it tells me that it cant read the content. Then the ppt is white.

My session.info():
R version 3.6.3 (2020-02-29)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

Matrix products: default

locale:
[1] LC_COLLATE=Spanish_Peru.1252  LC_CTYPE=Spanish_Peru.1252   
[3] LC_MONETARY=Spanish_Peru.1252 LC_NUMERIC=C                 
[5] LC_TIME=Spanish_Peru.1252    

attached base packages:
[1] grid      stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] ggalt_0.4.0     officer_0.3.8   lubridate_1.7.4 forcats_0.5.0   stringr_1.4.0  
 [6] dplyr_0.8.5     purrr_0.3.3     readr_1.3.1     tidyr_1.0.2     tibble_2.1.3   
[11] ggplot2_3.3.0   tidyverse_1.3.0 openxlsx_4.1.4  gtrendsR_1.4.4 

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.3         lattice_0.20-38    digest_0.6.25      assertthat_0.2.1  
 [5] proj4_1.0-10       R6_2.4.1           cellranger_1.1.0   backports_1.1.5   
 [9] reprex_0.3.0       httr_1.4.1         pillar_1.4.3       rlang_0.4.5       
[13] uuid_0.1-4         readxl_1.3.1       rstudioapi_0.11    extrafontdb_1.0   
[17] Matrix_1.2-18      labeling_0.3       splines_3.6.3      extrafont_0.17    
[21] munsell_0.5.0      broom_0.5.5        compiler_3.6.3     modelr_0.1.6      
[25] pkgconfig_2.0.3    mgcv_1.8-31        tidyselect_1.0.0   fansi_0.4.1       
[29] crayon_1.3.4       dbplyr_1.4.2       withr_2.1.2        MASS_7.3-51.5     
[33] Rttf2pt1_1.3.8     nlme_3.1-144       jsonlite_1.6.1     gtable_0.3.0      
[37] lifecycle_0.2.0    DBI_1.1.0          magrittr_1.5       scales_1.1.0      
[41] KernSmooth_2.23-16 zip_2.0.4          cli_2.0.2          stringi_1.4.6     
[45] farver_2.0.3       fs_1.3.2           xml2_1.2.5         vctrs_0.2.4       
[49] generics_0.0.2     ash_1.0-15         RColorBrewer_1.1-2 tools_3.6.3       
[53] glue_1.3.2         maps_3.3.0         hms_0.5.3          colorspace_1.4-1  
[57] rvest_0.3.5        haven_2.2.0    

What can i do? help please

The image of the ggplot
![image](https://user-images.githubusercontent.com/59374884/77560896-01a09780-6e8c-11ea-9532-9a525e443b29.png)

**Comment by davidgohel** [comment] 2020-03-25 16:38
Sorry. I'd like to help you but you are not following the guidelines described (when you open a new issue). The code you sent is not reproducible and you did not provide the sessionInfo() results. Could you update the issue please?

I will reopen when this will be done

**Comment by luis-zapata-b** [comment] 2020-03-25 17:25
what are the gguidelines? where can i reach them?

**Comment by davidgohel** [comment] 2020-03-25 17:27
They can be seen when you open a new issue:

<img width="753" alt="Capture d’écran 2020-03-25 à 18 26 37" src="https://user-images.githubusercontent.com/4331618/77566636-3d585300-6ec6-11ea-9f51-b78b019362c9.png">

**Comment by davidgohel** [comment] 2020-03-25 17:28
Also on the readme page:

<img width="940" alt="Capture d’écran 2020-03-25 à 18 28 12" src="https://user-images.githubusercontent.com/4331618/77566802-72fd3c00-6ec6-11ea-9aa4-bd8e12fd1c16.png">

Thanks

**Comment by luis-zapata-b** [comment] 2020-03-25 17:58
Im having the same problem with all my old codes that used to work. I dont know if its a problem with everyone with Office 360 and ggplot or just myself. Im going to try to replicate it!

**Comment by davidgohel** [comment] 2020-03-25 18:02
Thank you. For example, I don't have `z` so I am unable to execute your code

**Comment by luis-zapata-b** [comment] 2020-03-25 19:06
Anyway, i have this replicable code:

library(ggplot2)
library(officer)
library(tidyverse)

p = ggplot(iris,aes(x=Species)) +
  geom_bar()

read_pptx() %>%
  add_slide(layout = "Blank",master="Office Theme") %>% 
  ph_with(value = p, 
          location = ph_location_fullsize() ) %>%
  print("plot.pptx")

The plot.pptx file is just white, with nothing inside. Is just my computer? I dont know what to do.

**Comment by john-harrold** [comment] 2020-03-25 19:52
This  seems to work for me. I've included a screenshot of powerpoint. The figure loos the same as the variable 'p' does. My session info is below. 

<img width="1118" alt="image" src="https://user-images.githubusercontent.com/3170004/77579240-382fdf80-6e97-11ea-8b6e-1d03ec9ac7c1.png">


> sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.6

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] magrittr_1.5  officer_0.3.5 ggplot2_3.2.1

loaded via a namespace (and not attached):
 [1] zip_2.0.4        Rcpp_1.0.2       pillar_1.4.2     compiler_3.6.1  
 [5] base64enc_0.1-3  tools_3.6.1      digest_0.6.21    uuid_0.1-2      
 [9] tibble_2.1.3     gtable_0.3.0     nlme_3.1-140     lattice_0.20-38 
[13] pkgconfig_2.0.3  rlang_0.4.5      withr_2.1.2      dplyr_0.8.3     
[17] xml2_1.2.2       generics_0.0.2   grid_3.6.1       tidyselect_0.2.5
[21] glue_1.3.1       R6_2.4.0         tcltk_3.6.1      purrr_0.3.3     
[25] scales_1.0.0     htmltools_0.3.6  assertthat_0.2.1 colorspace_1.4-1
[29] labeling_0.3     lazyeval_0.2.2   munsell_0.5.0    crayon_1.3.4

**Comment by luis-zapata-b** [comment] 2020-03-25 20:03
Yes. I tried on an older computer with and older version of R and Office, and it worked. I dont know what to do, so im gonna reinstall office or install R 3.6.1

**Comment by davidgohel** [comment] 2020-03-25 20:05
No don't for now, I will try to have a look later this evening. However r version is never the issue.

**Comment by john-harrold** [comment] 2020-03-25 20:32
> Yes. I tried on an older computer with and older version of R and Office, and it worked. I dont know what to do, so im gonna reinstall office or install R 3.6.1

Have you tried opening the powerpoint file generated on your original computer (the one where you get a blank page) and open that file on the other computer that has an older version of R?

**Comment by luis-zapata-b** [comment] 2020-03-25 21:02
Yes. And it was empty. I have reinstalled office, and the problem remains the same.

[plot.pptx](https://github.com/davidgohel/officer/files/4383515/plot.pptx)

**Comment by luis-zapata-b** [comment] 2020-03-25 21:04
Have you download it? I just tried to change the design in the ppt and the image appeared! What is wrong with my computer x.x but you have seen my code, i just used location = ph_location_fullsize()

**Comment by john-harrold** [comment] 2020-03-25 21:36
When I open up the power point file in powerpoint it is blank. However on the Mac it will create previews of files when you hit the space bar. When I do that it works fine.

**Comment by luis-zapata-b** [comment] 2020-03-25 21:37
Ok! I've found my problem. Whenever i add a "Blank" layout, the ggplot image doesnt appear.
add_slide(layout = "Blank",master="Office Theme") . When i change  that to another layout, it works again. Its weird, because the same code works in my older computer.

Hope you can see the bug. Thanks for your time. Eventhoug, when i use the add_slide in a loop, the first time the pptx is damaged (the second time works fine). 

I think i cant work with it. Thanks.

**Comment by davidgohel** [comment] 2020-03-25 23:02
There are two issues explained here. 

The one with invisible image is a duplicate of #287 that has just been fixed. Please install the github version to get the fix. 

**About the second one**

Would you mind show me a simple code that demo your issue when using a loop?

The following code is ok on my computer:

```
library(ggplot2)
library(officer)

p = ggplot(iris,aes(x=Species)) +
  geom_bar()

doc <- read_pptx()
for(i in 1:5){
  doc <- doc %>%
    add_slide(layout = "Blank",master="Office Theme") %>% 
    ph_with(value = p, 
            location = ph_location_fullsize() ) 
}
print(doc, "plot.pptx") 
```


<img width="1558" alt="Capture d’écran 2020-03-26 à 00 00 17" src="https://user-images.githubusercontent.com/4331618/77593643-cedeb980-6ef4-11ea-96e3-ea7364148dbd.png">

**Comment by davidgohel** [comment] 2020-03-30 13:37
@luis-zapata-b I am closing the issue as I am not able to reproduce what you are describing with the loop. I will reopen if you can produce a reprex or provide information that let me understand/reproduce it.

**Closed by davidgohel** 2020-03-30 13:37 UTC
Labels: bug, duplicate, need for further details
