### ISSUE TITLE
embedding video files

### ISSUE THREAD

**Issue by JohnCamus** [davidgohel/officer#366] opened 2021-05-14 23:02 UTC
First of all, thank you so much to this community, especially david gohel, for creating this package. You saved me hours upon hours of manual effort in creating regular usability reports (I test whether users can actually use software).

automatically embedding text an images is making my life way easier than it should be. I just wondered whether there will be any function in the future that allows users to add .mp4 videos as well. I tend to show multiple live clips of users being bewildered or how they fail at some task. Videos just work better than pictures in this case.

At the moment, I add them by hand, after creating the pptx file. I am considering learning vba to do this programatically as well. 
So, I was just wondering whether video implementation will be a function or whether I should go and learn some vba.

Thank you so much for the package again. One menial task less I have to worry about.

**Comment by davidgohel** [comment] 2021-05-17 08:05
Thanks,

This is a duplicate of #346 and will be implemented (one day...)

**Closed** 2021-05-17 08:06 UTC
