### ISSUE TITLE
Could not write... [Can't open zip file]

### ISSUE THREAD

**Issue by mikgh** [davidgohel/officer#108] opened 2018-02-02 12:47 UTC
Hi,

Thank you for this great package. I already read a closed topic on this but it did not solve anything for me, unfortunately.

Upon executing the following code:
```
pres <- read_pptx()
print(pres, target = "h:\\test.pptx")
```

I get the following error:

> Could not write "h:/test.pptx" [Can't open zip file]

I have tried various paths that I know I have write access to but nothing helps. I have also ensured that the zip-package is installed and loaded.

sessionInfo here:
```
R version 3.4.3 (2017-11-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 15063)

Matrix products: default

locale:
[1] LC_COLLATE=Danish_Denmark.1252  LC_CTYPE=Danish_Denmark.1252    LC_MONETARY=Danish_Denmark.1252
[4] LC_NUMERIC=C                    LC_TIME=Danish_Denmark.1252    

attached base packages:
[1] grid      stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] magrittr_1.5         officer_0.2.0        forcats_0.2.0        stringr_1.2.0        dplyr_0.7.4         
 [6] purrr_0.2.4          readr_1.1.1          tidyr_0.7.2          tibble_1.4.1         ggplot2_2.2.1       
[11] tidyverse_1.2.1      srvyr_0.2.2          survey_3.32-1        survival_2.41-3      Matrix_1.2-12       
[16] scales_0.5.0         extrafont_0.17       zip_1.0.0            RevoUtils_10.0.7     RevoUtilsMath_10.0.1

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.14      lubridate_1.7.1   lattice_0.20-35   assertthat_0.2.0  digest_0.6.13     psych_1.7.8      
 [7] R6_2.2.2          cellranger_1.1.0  plyr_1.8.4        httr_1.3.1        pillar_1.0.1      rlang_0.1.6      
[13] uuid_0.1-2        lazyeval_0.2.1    readxl_1.0.0      rstudioapi_0.7    extrafontdb_1.0   R.utils_2.6.0    
[19] R.oo_1.21.0       splines_3.4.3     foreign_0.8-69    munsell_0.4.3     broom_0.4.3       compiler_3.4.3   
[25] modelr_0.1.1      pkgconfig_2.0.1   base64enc_0.1-3   mnormt_1.5-5      htmltools_0.3.6   crayon_1.3.4     
[31] R.methodsS3_1.7.1 nlme_3.1-131      jsonlite_1.5      Rttf2pt1_1.3.5    gtable_0.2.0      cli_1.0.0        
[37] stringi_1.1.6     reshape2_1.4.3    bindrcpp_0.2      xml2_1.1.1        tools_3.4.3       glue_1.2.0       
[43] hms_0.4.0         parallel_3.4.3    colorspace_1.3-2  rvest_0.3.2       bindr_0.1         haven_1.1.0  
```

I use Microsoft Open R but the same issue is reproducible in the CRAN version of R.

Thanks for any help you may provide. And of course I will provide all necessary info you may require.

Best regards,
Mikkel

**Comment by mikgh** [comment] 2018-02-02 19:31
Two notes two add:
- I tried officer on my home setup and the error persists
- Both my work and private PCs use Windows 10 (64-bit)

Best regards,
Mikkel

**Comment by mikgh** [comment] 2018-02-08 14:34
Apparently writing the full path in the print-function works.

**Comment by davidgohel** [comment] 2018-02-09 09:24
Hello, sorry for the delay

I can reproduce thanks. I don't know yet what is causing that issue :/

**Comment by davidgohel** [comment] 2018-02-09 09:25
What do you mean by *writing the full path in the print-function*?

**Comment by mikgh** [comment] 2018-02-09 10:25
Relative path does not work:
`print(pres, target = "out/test.pptx")`

Full path works:
`print(pres, target = "c:/abc/out/test.pptx")`

NOTE:
Neither of above methods worked a week ago. I am trying to think of what I have done to at least be able to save using the full path. I think I followed the instructions in this post:
https://stackoverflow.com/questions/27952451/error-zipping-up-workbook-failed-when-trying-to-write-xlsx

and specified the full path to the zip-package:
`Sys.setenv(R_ZIPCMD= "C:/SOMETHING_PATH/R_PACKAGE_FOLDER/zip") `

I also did try reinstall Rtools. Whether any of the two actually made it possible to at least save using the full path, I cannot say. I do think, though, that it could be something related to the zip-package causing the error.

**Comment by davidgohel** [comment] 2018-02-09 10:34
I just understood one issue:

``
> target <- "c:\\test.pptx"
> file.create(target)
[1] FALSE
Warning message:
In file.create(target) :
  cannot create file 'c:\test.pptx', reason 'Permission denied'
``

Could you run the following code and provide then the result:

``
target <- "H:\\test.pptx"
file.create(target)
``

> relative path 

I can't reproduce that one:
``
print(pres, target = "out/test.pptx")
``

Rtools is not used by the package so it has nothing to do with the issue. It uses package zip.

**Comment by mikgh** [comment] 2018-02-09 15:34
Tried it on my home PC (where I am unable to save even using the full path):
```
target <- "C:\\test.pptx"
file.create(target)
[1] FALSE
Warning message:
In file.create(target) :
  cannot create file 'C:\test.pptx', reason 'Permission denied'
```

**Comment by mikgh** [comment] 2018-02-09 15:46
Odd, just installed Microsoft Open R (64-bit) on my home PC and ran the following code (everything worked):
```
> library(officer)
> pres <- read_pptx()
> print(pres, target = "d:\\test.pptx")
[1] "d:/test.pptx"
> getwd()
[1] "C:/Users/mikke/Downloads"
> print(pres, target = "test.pptx")
[1] "C:/Users/mikke/Downloads/test.pptx"
> target <- "d:\\test.pptx"
> file.create(target)
[1] TRUE
```

**Comment by mikgh** [comment] 2018-02-09 16:16
Alright, here is a summary of the current status:

On work PC:
- I cannot save using relativ path
- I CAN save using full path
- `print(pres, target = "H:/FULL PATH/test.pptx")` works

On home PC:
- I can save using both full and relative path
- It works in both base R 3.4.3 and Microsoft Open R 3.4.3

I am at the point where I DO think it could be a access permission issue rather than something in your package :-/

**Comment by davidgohel** [comment] 2018-02-09 16:35
OK

Be careful with MRO, you are getting packages from a *date point* and not necessary the last versions. (in general always get the sessionInfo() to check that)

Yes, it seems to be a permission problem, I will try to find a way to test for that case, don't know yet exactly how but I will find out :) I will close the issue when it will be done.

PS : Some users have met issues with accents in filename (because of an UTF-8 encoding issue), maybe that related...

**Comment by davidgohel** [comment] 2018-02-15 11:53
OK, I have set up a better checking... https://github.com/davidgohel/officer/blob/master/R/pack_folder.R#L16

Should be better now.

**Closed by davidgohel** 2018-02-15 11:53 UTC
Labels: bug
