### ISSUE TITLE
body_replace_all_text with hyperlink

### ISSUE THREAD

**Issue by tdelc** [davidgohel/officer#432] opened 2022-06-09 11:38 UTC
Hi,

I would to replace some text with a hyperlink into a docx file. I think that it could be possible to do that with locate the text, remove it, and then add a hyperlink, but I have some difficulty to put the cursor in the good position.

Is it difficult to adapt the _body_replace_all_text_ function, or to create an other function to locate text by regex, and then replace it by a hyperlink ? I think it would by a very nice enhancement.

Sorry if the solution already exists, I do not find it.

**Comment by davidgohel** [comment] 2022-06-09 11:57
Hello. Please, provide a reproducible example

**Comment by tdelc** [comment] 2022-06-09 12:04
It is not possible de provide a reproducible example, because the feature does not exists already.

Ideally, it will be fine if this kind of function could work :
`doc <- body_replace_all_text(doc,"text to find",hyperlink_ftext("text to find",href = "url"))`

From now, i do this : 
`doc <- cursor_reach(doc,"text to find")
doc <- cursor_backward(doc)
doc <- body_replace_all_text(doc ,"text to find","",only_at_cursor = TRUE)
doc <- slip_in_text(doc, "text to find",pos = "after", hyperlink = "url")`

**Comment by davidgohel** [comment] 2022-06-09 12:16
OK, I'll take time to define a reproducible example later when I'll find time.

**Comment by tdelc** [comment] 2022-06-09 12:29
Thanks!

**Comment by davidgohel** [comment] 2022-12-19 08:27
Here is an example that works for me:

```
doc <- read_docx()
doc <- body_add_par(doc, "blah blah blah")
doc <- body_add_par(doc, "blah blah blah")
doc <- body_add_par(doc, "blah blah blah")
doc <- body_add_par(doc, "Hello text to replace")
doc <- body_add_par(doc, "blah blah blah")
doc <- body_add_par(doc, "blah blah blah")
doc <- body_add_par(doc, "blah blah blah")
doc <- body_add_par(doc, "Hello text to replace")
doc <- body_add_par(doc, "blah blah blah")
template_file <- print(
  x = doc,
  target = tempfile(fileext = ".docx"))

doc <- read_docx(path = template_file)
# while (!inherits(try(cursor_reach(doc, "to replace")), "try-error")) { # use this line if officer < 0.4.5
while(cursor_reach_test(doc, "to replace")) { # use this line if officer >= 0.4.5
  doc <- cursor_reach(doc, "to replace")
  
  doc <- body_add_fpar(
    x = doc,
    pos = "on",
    value = fpar(
      "Here is a link: ",
      hyperlink_ftext(
        text = "yopyop",
        href = "https://cran.r-project.org/"
      )
    )
  )
}

doc <- cursor_end(doc)
file <- print(doc, target = tempfile(fileext = ".docx"))
if(doconv::msoffice_available()) browseURL(file)
```

**Comment by davidgohel** [comment] 2022-12-20 22:57
Closing the question, let me know if you have questions about it.

**Closed by davidgohel** 2022-12-20 22:57 UTC
