### ISSUE TITLE
complex templates produce invalid pptx file

### ISSUE THREAD

**Issue by wdearden208** [davidgohel/officer#43] opened 2017-07-21 16:47 UTC
When reading in a .pptx with template layouts, if the slide layout has an image, then PowerPoint will print out that there is unreadable content. This is replicated with my employers's PowerPoint template, which I can't use here, and a bunch of other templates I found online.

As an example:

Download the [Wharton Powerpoint template](https://standards.wharton.upenn.edu/wp-content/uploads/2014/06/branded_ppt_template.pptx) and save in working directory as `template.pptx`. Sorry for the manual work, for whatever reason `download.file` does not work well with `.pptx` for me.
```
library(officer)
library(magrittr)

officer_example <- read_pptx("template.pptx") %>%
  add_slide(layout = "Deck Cover", master = "knowledge_master1-3_theme") %>%
  ph_with_text(type = "title", str = "A title")

print(officer_example, target = "officer.pptx") %>% invisible()
```

When I open `officer.pptx` I get the error message `PowerPoint removed unreadable content in officer.pptx. You should review this presentation to determine whether any content was unexpectedly changed or removed`. On the new slide, slide 19, the image still appears but there is a box over it which says `This image cannot currently be displayed.`

In other examples, the image won't even appear. For example, save the [Kellogg PowerPoint template](http://www.kellogg.northwestern.edu/mar-comm/downloads.aspx) as `Kellogg_Template_4x3.pptx` in the working directory. Then run:

```
kellogg_example <- read_pptx("Kellogg_Template_4x3.pptx") %>%
  add_slide(layout = "Title Slide", master = "Custom Design")

print(kellogg_example, target = "kellogg_officer.pptx") %>% invisible()
```

Just to add, I get mixed results with doing the equivalent in `ReporteRs`. With my corporate theme, it actually works perfectly but in other examples there is technically no error but it loses the theme.

**Comment by davidgohel** [comment] 2017-07-21 17:35
I can reproduce everything, thanks for the reproducibility!

I will have a look at that next week. 

david

**Comment by davidgohel** [comment] 2017-07-24 17:10
Issue is ... interesting.

When manually unzipping the template, I got one more file than when using programatic tools:
unzip (the R function), package archive, unzip (command line) and java. (it needs to unzip the template to be able to modify it).

I don't have solution yet nor real explanation (maybe something with the file path length of the missing file which is very long - some unzip version have trouble with file paths > 256 characters).

**Comment by wdearden208** [comment] 2017-07-24 17:21
Something isn't working with `download.file` and `.pptx`. See [this snippet](http://www.sthda.com/english/wiki/create-and-format-powerpoint-documents-from-r-software#download-a-template-file):

```
download.file(url="http://www.sthda.com/sthda/RDoc/example-files/r-reporters-powerpoint-template.pptx",
    destfile="r-reporters-powerpoint-template.pptx", quiet=TRUE)
```
which creates an unreadable file but is a perfectly valid file if I visit the URL on my browser.

Just want to be clear my issue above is unrelated to the `download.file` issue though.

**Comment by davidgohel** [comment] 2017-07-24 17:29
no problem, I did manually download the file and can edit it.

**Comment by md0u80c9** [comment] 2017-08-31 22:14
Hi,

Just to say I've encountered this problem as well this evening (the same powerpoint template was working fine with ReporteRs but doesn't work with officer).

I can't post my .pptx publicly but can share privately for bug fixing purposes if it helps.

**Comment by davidgohel** [comment] 2017-08-31 22:18
Hi, yes, please PM me the template.

**Comment by EDiLD** [comment] 2017-09-11 10:39
I see the same problem.

![capture](https://user-images.githubusercontent.com/849616/30270714-de1bdbe4-96ed-11e7-967e-00b4c684a1d3.PNG)

I am basically only using `ph_with_text()`. 
Interestingly, it works on my local machine, but not on a remote server (maybe some differences in system libraries?).

**Comment by xvrdm** [comment] 2017-09-14 09:33
Same problem here on windows 10. Also only using `ph_with_text()` on a layout with images. 
Presentation is working in ReporteRs.

**Comment by xvrdm** [comment] 2017-09-18 13:14
It's only tiny clue but after more testing, it looks like it is images in layout that cause the bug. When there are only images in the master, the file gets generated (I see lots of other issues with placeholder missing but this might be due to my bad understanding of the package at this stage).

**Comment by davidgohel** [comment] 2017-09-18 21:49
I think I finally find the issue (wrong xpath... sorry!). 

It should be ok now, if not, ask to reopen the issue.

**Comment by davidgohel** [comment] 2017-09-18 21:54
@EDiLD Maybe you are facing a different issue, this issue was totally reproducible but you are describing something that work on a machine and does not and another. If that fix doesn't solve your issue, open a new one and add your sessionInfo() (two if working on two different machine) and a reproducible example.

**Comment by EDiLD** [comment] 2017-09-19 04:50
Thanks David for looking at this.
I'll check and report back.

Mit AquaMail Android
http://www.aqua-mail.com gesendet


Am 18. September 2017 11:54:49 PM schrieb David Gohel 
<notifications@github.com>:

**Comment by wdearden208** [comment] 2017-09-19 23:07
Thanks! I tried it with my corporate template. Interestingly there is a logo in the opening slide and it appeared correctly. But there is also a logo in the closing slide layout and it did not appear. I do not get an error related to unreadable content; the logo just does not appear.

I will see if I can email you the corporate template.

**Comment by davidgohel** [comment] 2017-09-20 16:52
thanks. I tried with `branded_ppt_template.pptx` and did not detect any issue but I may have forgotten to check something...

**Comment by davidgohel** [comment] 2017-09-20 20:02
OK, got it now ;)

**Comment by md0u80c9** [comment] 2017-09-20 20:43
Woohoo! Let me know when the updated version will be available from RStudio. officeR is now one of our core packages for our project :-).

**Comment by YourEconProf** [comment] 2017-09-23 20:12
This still doesn't work for me for my personal template. It has a different background for the title slide than the other slides. I have attached the pptx file. When I use the following code, the "Title and Content" works fine, but the "Title Slide" background image won't display.
```
library(officer)
library(magrittr)

# Load PPTX file:
pptx_file = read_pptx(path = 'officer-test.pptx')
pptx_file = pptx_file %>% add_slide(layout="Title Slide", master="Office Theme") %>%
  ph_with_text(type = "ctrTitle", str = "This is a title") %>%
  ph_with_text(type = "subTitle", str = "This is a subtitle") 
  
pptx_file = pptx_file %>% add_slide(layout="Title and Content", master="Office Theme") %>%
  ph_with_text(type = "body", str = "Test 1 \nTest 2", index = 1) %>%
  ph_with_text(type = "title", str = "This is a title")

print(pptx_file, target = 'officer-test-out.pptx') %>%
  invisible()


```


[officer-test.pptx](https://github.com/davidgohel/officer/files/1326823/officer-test.pptx)

**Comment by davidgohel** [comment] 2017-09-28 16:09
@YourEconProf It should be OK now. Can you test?

**Comment by wdearden208** [comment] 2017-09-28 16:20
Works with the template I emailed you.

**Comment by davidgohel** [comment] 2017-09-28 17:04
OK, I am closing the issue (hopefully for the last time)

**Closed by davidgohel** 2017-09-28 17:04 UTC
Labels: bug

**Comment by YourEconProf** [comment] 2017-09-29 18:33
Hopefully I can still comment to say that this does indeed work just fine now. Thanks so much.

**Comment by WilDoane** [comment] 2017-10-05 18:56
I'm afraid it's not dead yet... running 0.1.8.0002, I still get a corrupt file error with a corporate template.

    library(ggplot2)
    library(officer)
    library(dplyr)
    
    gg <- 
      ggplot(mtcars, aes(cyl, hp)) + 
      geom_point()
    
    temp_filename <- tempfile(fileext = ".png")
    png(temp_filename, res = 150)
    print(gg)
    dev.off()
    
    read_pptx() %>% 
      add_slide(layout = "Title and Content", master = "Office Theme") %>% 
      ph_with_img(temp_filename, type = "body") %>% 
      add_slide(layout = "Title and Content", master = "Office Theme") %>% 
      ph_with_img(temp_filename, type = "body") %>% 
      print(target = "demo_basic.pptx")
    
    
    
    # corporate template ------------------------------------------------------
    
    read_pptx("corporate.potx") %>% 
      add_slide(layout = "Center Takeaway", master = "ACME") %>% 
      ph_with_img(temp_filename, type = "body") %>% 
      add_slide(layout = "Center Takeaway", master = "ACME") %>% 
      ph_with_img(temp_filename, type = "body") %>% 
      print(target = "demo_corporate.pptx")
    
I can send you the template and resulting PPTX files offline, if you like. Contact me at wil@DrDoane.com

**Comment by davidgohel** [comment] 2017-10-05 19:20
@WilDoane `potx` files are not supported, you can save it as a empty pptx and it should be ok

**Comment by julissamartinez** [comment] 2019-01-02 22:01
Hi,

I am still encountering a similar problem. I can PM you my template. 

The error I get is "PowerPoint removed unreadable content in the file TEST18.ppptx. You should review this presentation to determine whether any content was unexpectedly changed or removed." and when I open the powerpoint I see an x with this message "The image cannot be displayed. Your computer may not have enough memory to open the image, or the image may have been corrupted. Restart your computer, and then open the file again. If the red x still appears, you maybe have the image and then insert it again."

I have tried to do those things and still no luck.

**Comment by davidgohel** [comment] 2019-01-02 22:10
@julissamartinez please open an new issue (and follow the guidelines)

**Comment by julissamartinez** [comment] 2019-01-02 23:41
Hi David,

I opened up a new issue. https://github.com/davidgohel/officer/issues/172.
I am attaching the template.

Thanks in advance,

Julissa
