### ISSUE TITLE
need for a copy method

### ISSUE THREAD

**Issue by DiegoNOB** [davidgohel/officer#137] opened 2018-05-30 19:51 UTC
Hello,
when adding slides to a certain pptx object, other objects get new slides too. Example:

> pptx1 <- read_pptx()
> pptx2 <- pptx1
> length(pptx1)
[1] 0
> length(pptx2)
[1] 0
> pptx1 <- add_slide(pptx1,layout="Title Slide",master="Office Theme")
> length(pptx1)
[1] 1
> length(pptx2)
[1] 1

So, pptx2 has now 1 slide, even though I added the new slide only to pptx1. Am I missing something here? Thanks

**Comment by davidgohel** [comment] 2018-05-31 10:43
No you are not missing anything. These objects are made with R6 classes and also map a temporary directory. Copying the object does not duplicate the temporary directory where the xml are stored and the R6 objects should be clone also. 

I suppose the use case you are showing is not really representative of what you want to do. If possible, could you explain more your context (why you want to copy these objects)?

KR
David

**Comment by DiegoNOB** [comment] 2018-05-31 19:00
Hi David, thanks for the quick response. I'll explain my situation:
I have a personalized pptx template and a dataset with roughly 20.000 individuals (rows). I need to create a PowerPoint file for each one of them, which I do by adding text and plots that vary from individual to individual . The thing is, I don't want to read my template 20.000 times; I just want to read it one time and then do something like this:

> mypptx <- read_pptx()
> foo <- 1:3
> for (j in foo) {
        z <- mypptx
        z <- add_slide(z,layout="Title and Content",master="Office Theme")
        z <- ph_with_text(z,paste0("Title ",j),type="title")
        print(z,target=paste0("File",j,".pptx"))
 }

Running this code results in File1 having 1 slide, File2 having 2 slides and File3 having 3 slides. I just want one slide in each of them. I know I can accomplish this by writing z <- read_pptx() at the beginning of the loop, but that's exactly what I want to avoid since it will be really time-consuming.
Hope I made my point clear. Thanks again

Diego

**Comment by davidgohel** [comment] 2018-06-03 13:53
I understand your case, thanks for explaining it! I think I will need time to find a solution.

That implies a big change: an object is mapped to a temporary directory where all xml are stored and manipulated. A copy implies to duplicate these files for each copy and update internal objects linked to files. 

David

**Comment by davidgohel** [comment] 2019-04-28 19:29
Hi

Sorry, I am closing that issue as it implies too much refactoring for now. I may reopen later (hopefully)

**Closed by davidgohel** 2019-04-28 19:29 UTC
Labels: enhancement

**Comment by Ljupch0** [comment] 2021-06-28 13:56
Just to add another use case - I am also experiencing this issue. In my case I have a shiny app that generates various reports. I have a template() reactive that reads in the needed pptx template based on user selection. The issue is if the user generates several reports based on the same template in succession and the template() reactive is not updated, the slides from previous reports show up in the new ones. Thank you for the hard work @davidgohel.
