### ISSUE TITLE
Using annotate_base() and getting an index error that I don't know how to interpret or fix

### ISSUE THREAD

**Issue by akaEmma** [davidgohel/officer#151] opened 2018-09-20 16:45 UTC
I'm using the latest version of the officer package.

Here is the code, where template.pptx is a powerpoint file (attached) whose master slides have been altered to match my client's requirements:

    template_file = "template.pptx"
    annotate_base(path = template_file, output_file = "annotated_layout.pptx")
    
The file contains only one slide master with five layouts defined within it. It does not contain any slides. 

Here is the output:

    Error in slide$get_xfrm(type = type, index = index) : body can only have 5 element(s) but index is set to 6

Why?

Thanks for any help. I love this package & hope I can make it work.

[template.pptx](https://github.com/davidgohel/officer/files/2402301/template.pptx)

**Comment by akaEmma** [comment] 2018-09-21 18:03
...and just like that, the bug is gone. I haven't changed a thing except closing R, sleeping, and starting it up again. Environmental confusion? Dunno.

**Comment by abidawson** [comment] 2018-09-23 19:35
I've seen a similar error in my use of this package recently when using the `ph_with` functions and I think I might be able to help point toward the source of the error here. I replicated the error that @akaEmma is getting with this template file. 

The error seems to be coming from `get_xfrm` in `ppt_classes.R`, copied below. Part of this function checks whether the index is outside the length of the `type` placeholder matches for a given layout.

```
get_xfrm = function(type = NULL, index = 1){
      out <- private$element_data
      if( !is.null(type) ){
        if( type %in% out$type ){
          type_matches <- which( out$type == type )
          if( index <= length(type_matches) )
            id <- type_matches[index]
          else stop(type, " can only have ", length(type_matches), " element(s) but index is set to ", index)

        } else stop("type ", type, " is not available in the slide layout")
        out <- out[id, ]
      }
      out
    },
```

 However, the index values for placeholders are often not nicely numbered. For example, in the output below, there are 7 `body` placeholders for the "Culture_Values_Slide" layout, but the `id` values are 3,5,6,7,8,9, and 10. 8,9, and 10 will give errors as being outside the length of the `type_matches`. 

```
template_file = "template.pptx"
template <- read_pptx(template_file)
lp <- layout_properties(template)
subset(lp, name == "Culture_Values_Slide" & type == "body")
   master_name                 name type id                   ph_label      offx      offy        cx
14      Sigbar Culture_Values_Slide body  3                Rectangle 2 0.0000000 0.2500000  9.333333
15      Sigbar Culture_Values_Slide body  5                Rectangle 2 1.0000000 0.5902778  8.500000
16      Sigbar Culture_Values_Slide body  6                Rectangle 4 0.1655249 1.6016350  9.916667
17      Sigbar Culture_Values_Slide body  7                Rectangle 3 0.0000000 0.3217192 10.000000
18      Sigbar Culture_Values_Slide body  8                Rectangle 4 0.1769412 1.0000000  9.999999
19      Sigbar Culture_Values_Slide body  9                  TextBox 8 0.1655238 6.8333333  9.999999
20      Sigbar Culture_Values_Slide body 10 Slide Number Placeholder 2 7.8333333 7.2673611  2.333333
          cy
14 0.7500000
15 0.4270833
16 5.1483650
17 0.6065617
18 0.4236210
19 0.4039064
20 0.3993056

```

I don't get this type of error when I use an earlier version of the package such as 0.1.8. 

I hope this is helpful to get the issue resolved in the package. In the meantime, if anyone knows of a way to renumber the `id` values of a layout either in Powerpoint or in R, that might be a way to get around the issue. I love this package and use it every day in my work, so any help here is much appreciated.

**Comment by davidgohel** [comment] 2018-09-23 21:32
@abidawson 

When using functions `ph_with_*`, you don't have to provide these id - these id are generated by MS PowerPoint, not officer. I should probably hide these numbers if they are confusing :)

You need to provide a simple index (default to 1). e.g. if your template has 2 *body* placeholder, you will need to specify that your content is to be positioned as the 2nd body of your layout (then use index 2). See for example https://davidgohel.github.io/officer/reference/ph_with_text.html

(If I misunderstood something, please open an new issue with a reproducible example)

**Comment by abidawson** [comment] 2018-09-23 21:35
@davidgohel Yes, I think I misunderstood the usage of index vs id, and this is a very helpful clarification - thank you!

**Comment by davidgohel** [comment] 2018-09-23 21:37
@abidawson thanks for the feedback (then it goes in docs!)

**Closed** 2018-10-26 15:52 UTC
