### ISSUE TITLE
Overlapping text, line break and ggplot in same cell of flextable

### ISSUE THREAD

**Issue by muranyia** [davidgohel/officer#374] opened 2021-06-07 23:41 UTC
Hi David,

When I insert a flextable into a docx, and the flextable has text, line break, and a ggplot in the same cells (using `compose()`),
they start to overlap.

The flextable itself, when printed, looks fine.

``` r
require(flextable)
ft <- flextable( head(iris, n = 10 ))
ft <- compose(ft, j = 1,
              value = as_paragraph(
                as_chunk(Sepal.Length),
                "\n ",
                minibar(value = Sepal.Length, max = max(Sepal.Length))
              ),
              part = "body")
ft <- width(ft, j=1:5, width=1.5)
ft # This looks fine

require(officer)
doc <- read_docx()
doc <- body_add_flextable(doc, ft)
print(doc, target="example.docx") # Here the contents overlap
```

**Comment by muranyia** [comment] 2021-06-09 21:07
While trying to find a workaround, I realized that the line break is not necessary to reproduce the symptom. 
Consider the following example:

```R
ft <- flextable( head(iris, n = 10 ))
ft <- compose(ft, j = 1,
              value = as_paragraph(
                as_chunk(Sepal.Length),
                " ",
                minibar(value = Sepal.Length, max = max(Sepal.Length), width=1.4, height=.5)
              ),
              part = "body")
ft <- width(ft, j=1:5, width=1.5)
ft

require(officer)
doc <- read_docx()
doc <- body_add_flextable(doc, ft)
print(doc, target="example.docx")
```

**Comment by davidgohel** [comment] 2021-07-20 19:07
Hi, 

It's because the first column don't have enough width. You have to increase width for first column:

```
library(flextable)
library(officer)

ft <- flextable( head(iris, n = 10 ))
ft <- compose(ft, j = 1,
              value = as_paragraph(
                as_chunk(Sepal.Length),
                " ",
                minibar(value = Sepal.Length, max = max(Sepal.Length), width=1.4, height=.5)
              ),
              part = "body")
ft <- width(ft, j=1:5, width=c(2, rep(1.5, 4)))
# ft <- autofit(ft) # easy solution
ft

require(officer)
doc <- read_docx()
doc <- body_add_flextable(doc, ft)
print(doc, target="example.docx")
```

As this is not a bug and more about flextable, I am closing the issue.

**Closed by davidgohel** 2021-07-20 19:07 UTC
