### ISSUE TITLE
problem with hyperlink_ftext

### ISSUE THREAD

**Issue by andrija-djurovic** [davidgohel/officer#417] opened 2022-04-13 16:48 UTC
Hi, 

I am facing the problem with hyperlink_ftext function. When I run the code below (extract from ?body_add_fpar example):
```
bold_face <- shortcuts$fp_bold(font.size = 30)
bold_redface <- update(bold_face, color = "red")
rlogo <- file.path( R.home("doc"), "html", "logo.jpg" )
img_in_par <- fpar(
  external_img(src = rlogo, height = 1.06/2, width = 1.39/2),
  hyperlink_ftext(
    href = "https://cran.r-project.org/index.html",
    text = "cran", prop = bold_redface),
  fp_p = fp_par(text.align = "center") )

doc <- read_docx()
doc <- body_add_fpar(doc, img_in_par)
print(doc, target =  "test.docx")
```
hyperlink does not work. 
More concretely when I edit it directly in Word test.docx it shows the following address:
https%3A/cran.r-project.org/index.html
When text cran is covered by the cursor I see some text before hyperlink which is basically the path to the file test.docx (file:///c:\user\... and then https:\cran.r-project.org/index.html).

Can you reproduce the same behavior or do you have idea how I can solve it?

Below are the session details:
R version 4.1.0 (2021-05-18)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] officer_0.4.2

loaded via a namespace (and not attached):
[1] compiler_4.1.0 R6_2.5.0       tools_4.1.0    uuid_0.1-4     xml2_1.3.2     zip_2.2.0 

Thank you.
Andrija

**Comment by davidgohel** [comment] 2022-04-17 08:19
Dear Andrija,

I can't reproduce on my mac machine. Could you post the docx you're getting as a result so that I can compare when I will work on that?

**Comment by andrija-djurovic** [comment] 2022-04-17 08:57
Dear David,

thanks a lot for reply and sorry for not posting previously all the files.
Here they are:
- Cursor hover:
![cursor](https://user-images.githubusercontent.com/85941317/163707642-5ccbd3af-2d2e-4fb0-afd6-3fd0b63dd8e1.png)

- Edited hyperlink
![edit_hyperlink](https://user-images.githubusercontent.com/85941317/163707692-a618a27c-f05b-478a-8b6f-c3228751b378.png)

- Docx file
[test.docx](https://github.com/davidgohel/officer/files/8501260/test.docx)


Thank you.
Andrija

**Comment by davidgohel** [comment] 2022-04-17 09:04
Thanks for answering so fast,

I can see I have the same content as you; but on my mac, Word does not assume some prefix should be added.

I will need to find a Windows machine to understand what is happening (this was supposed to be fixed... I remember some issues about that)!

**Comment by andrija-djurovic** [comment] 2022-04-17 09:12
Thanks David.

Looking forward to hearing back from you again. 
Let me know if I can assist somehow further (running some test or anything similar you consider as useful).

Andrija

**Comment by davidgohel** [comment] 2022-04-17 09:17
Thank you, 

(just to let you know, I will not work on that now, but I will in the next *development run*)

**Comment by davidgohel** [comment] 2022-12-13 08:09
hello,

it should be fixed now. I hope it is :)

David

**Closed** 2022-12-13 08:08 UTC
Labels: bug
