### ISSUE TITLE
Enhancement request: Manipulate PowerPoint slide notes

### ISSUE THREAD

**Issue by JasonParker** [davidgohel/officer#117] opened 2018-03-15 16:30 UTC
**Thanks so much for your work on this package**, I'm using it a lot to support a number of colleagues with PowerPoint slide decks showing data. 

**Enhancement request**: It would be very beneficial to be able to **add content to the notes section** of a slide in PowerPoint through the package. I'm making slides for many people with data tables, charts, and other content. There is information I'd like for the speaker to have at his/her disposal during the presentation that should not be available to the audience, and the slide notes would be a great place for this. Because I'm generating slide decks en masse, it would be very helpful to be able to add customized content to the notes based on the underlying data.

I'll admit that I know very little about the Office API that underlies the package or whether this is even possible. I have very little experience in package development, but this is something I'd be willing to support if it is a feature you believe is worth adding. Thanks.

**Comment by muschellij2** [comment] 2018-03-30 19:59
I agree with this.  Also - functionality to simply extract the notes from a powerpoint.

**Comment by muschellij2** [comment] 2018-03-30 20:19
Currently, you can at least read them in as follows:
``` r
[tmp.pptx](https://github.com/davidgohel/officer/files/1864688/tmp.pptx)
library(xml2)
library(rvest)
library(magrittr)
library(officer)
x = read_pptx("tmp.pptx")
notes_dir = file.path(x$package_dir, "ppt", "notesSlides")
files = list.files(pattern = ".xml$", 
                   path = notes_dir, full.names = TRUE)
xdoc = read_xml(files[1])
txt = xdoc %>% xml_find_all("//a:t") %>% xml_text()
txt = paste(txt, collapse = "\n")
cat(txt)
#> The best 
#> around
#> I wonder how a’asdf;lkajer;k23oiausdpoisjdf
#> Foafdpoiu3poriuadkf;lkj: ≥
#> 1
```

Created on 2018-03-30 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

I don't know how exactly the structure the reference classes @davidgohel made, so I'm hesitant to make a PR.

**Comment by davidgohel** [comment] 2018-04-02 08:10
Thanks all for your suggestions. This is a duplicate of #90. 

I will come back to this subject but not now as it implies lot of work and I don't have enough time for now.

**Comment by thercast** [comment] 2018-11-28 18:58
I'm very interested in this feature as well.  Since this issue has more details on possible solutions I'll add some information that we might use as reference:

In searching for other libraries that author powerpoint files, I found two javascript libraries that claim support for adding speaker notes to slides: [officegen](https://github.com/Ziv-Barber/officegen) and [PptxGenJS](https://github.com/gitbrent/PptxGenJS).  I haven't thoroughly examined the code yet, but I will look at these in more detail to see if it gives a good starting point.

**Comment by davidgohel** [comment] 2019-08-19 10:59
This issue is opened since too much time. Sorry. I will re open when I will find time for it

KR
David

**Closed by davidgohel** 2019-08-19 10:59 UTC
Labels: feature request
