### ISSUE TITLE
Cannot add file `[Content_Types].xml to archive

### ISSUE THREAD

**Issue by LukaszDerylo** [davidgohel/officer#258] opened 2019-11-25 14:18 UTC
After updating to officer 0.3.6 from 0.3.5 I started getting this kind of errors

```
Error in value[[3L]](cond) : 
  Could not write "C:/Users/Łukasz/Desktop/firma/dev/raport - Kopia.docx" [zip error: `Cannot add file `[Content_Types].xml` to archive `C:/Users/Łukasz/Desktop/firma/dev/raport - Kopia.docx`` in file `zip.c:394`] 

```
How can I resolve it?

```
> sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=Polish_Poland.1250  LC_CTYPE=Polish_Poland.1250    LC_MONETARY=Polish_Poland.1250
[4] LC_NUMERIC=C                   LC_TIME=Polish_Poland.1250    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] png_0.1-7       flextable_0.5.6 officer_0.3.6   glue_1.3.1      lubridate_1.7.4 magrittr_1.5   
 [7] forcats_0.4.0   stringr_1.4.0   dplyr_0.8.3     purrr_0.3.3     readr_1.3.1     tidyr_1.0.0    
[13] tibble_2.1.3    ggplot2_3.2.1   tidyverse_1.3.0

loaded via a namespace (and not attached):
 [1] xfun_0.11         tidyselect_0.2.5  haven_2.2.0       lattice_0.20-38   colorspace_1.4-1 
 [6] vctrs_0.2.0       generics_0.0.2    htmltools_0.4.0   base64enc_0.1-3   rlang_0.4.2      
[11] pillar_1.4.2      withr_2.1.2       DBI_1.0.0         gdtools_0.2.1     dbplyr_1.4.2     
[16] modelr_0.1.5      readxl_1.3.1      uuid_0.1-2        lifecycle_0.1.0   munsell_0.5.0    
[21] gtable_0.3.0      cellranger_1.1.0  rvest_0.3.5       zip_2.0.4         evaluate_0.14    
[26] knitr_1.26        broom_0.5.2       Rcpp_1.0.3        scales_1.1.0      backports_1.1.5  
[31] jsonlite_1.6      systemfonts_0.1.1 fs_1.3.1          hms_0.5.2         digest_0.6.23    
[36] stringi_1.4.3     grid_3.6.1        cli_1.1.0         tools_3.6.1       lazyeval_0.2.2   
[41] crayon_1.3.4      pkgconfig_2.0.3   zeallot_0.1.0     data.table_1.12.6 xml2_1.2.2       
[46] reprex_0.3.0      rmarkdown_1.17    assertthat_0.2.1  httr_1.4.1        rstudioapi_0.10  
[51] R6_2.4.1          nlme_3.1-142      compiler_3.6.1   
```

**Comment by LukaszDerylo** [comment] 2019-11-25 14:19
I have this error even when I try to save docx file to location without polish letters...

**Comment by davidgohel** [comment] 2019-11-26 07:43
Hi,

Please add a reproducible example :)

KR
David

**Comment by LukaszDerylo** [comment] 2019-11-26 09:36
Reproducible example is:

`read_docx() %>% print('raport - Kopia.docx')`

I overcomed this error simply by getting rid of polish letteres (letter Ł in my case) from Windows User name. Now my User name is "Lukasz" and `officer` uses path "C:/Users/Lukasz/Desktop" (no polish letters!) for temporary files and everything works again.

Still, I think this is an issue.

**Comment by davidgohel** [comment] 2019-11-26 18:09
OK, I see. 

(This happens because of zip package.) It only happens on windows platform. I don't know how to workaround that for now. I agree this would be good if solved. Maybe by writing the doc in tempfile() and then copy or move the result but that's not a good solution. I will take time later to open an issue in zip repo...

**Comment by davidgohel** [comment] 2020-07-14 20:59
Finally! It is fixed now (in the GitHub version).

**Closed by davidgohel** 2020-07-14 20:59 UTC
