### ISSUE TITLE
Certain hyperlinks in the body of a docx document break the document after saving.

### ISSUE THREAD

**Issue by alexmosc** [davidgohel/officer#426] opened 2022-05-26 08:16 UTC
Reproducible case:

- Open Word and create blank document
- Insert this hyperlink as a paragraph or in a table cell: **[https://tass.ru/kultura/13655719](https://tass.ru/kultura/13655719?utm_source=yandex.ru&utm_medium=organic&utm_campaign=yandex.ru&utm_referrer=yandex.ru)**, make it clickable (pressing space after)
- Save as input_doc_2.docx
- Open it with the `officer::read_docx`
- Save it with the `print` to a new file output_doc.docx
- Try to open output_doc.docx with the `officer::read_docx`

and here is the error:
> Error in doc_parse_file(con, encoding = encoding, as_html = as_html, options = options) : 
>   EntityRef: expecting ';' [23]

Try to open output_doc.docx with Word

`Cannot open because of its content`

Code:

```
setwd('....your directory....')

library(officer)
library(magrittr)

local_dir <- '/tests/'

file_path <- 'input_doc_2.docx'

input_doc <- 
  officer::read_docx(path = paste0(getwd(), local_dir, file_path))

input_doc %>%
  print(target = paste0(getwd(), local_dir, 'output_doc.docx'))

output_doc <-
  officer::read_docx(path = paste0(getwd(), local_dir, 'output_doc.docx'))
```

My _guess_ is that when saving a docx file, some function changes the XML code layout inside the `output_doc/word/document.xml` or somewhere else so that escaping gets broken for some symbols.

If the hyperlink is inserted as pure text, there is no error.

There are other hyperlinks I tested that cause this error, e.g., https://spec.tass.ru/avangard-na-shabolovke/?from=newsapp&utm_partner_id=149 (it also should be made clickable).

Session info:

```
> sessionInfo()
R version 3.6.0 (2019-04-26)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS:   /usr/local/lib64/R/lib/libRblas.so
LAPACK: /usr/local/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] magrittr_1.5      officer_0.3.8.006

loaded via a namespace (and not attached):
[1] compiler_3.6.0 R6_2.4.1       tools_3.6.0    Rcpp_1.0.3     uuid_0.1-4     xml2_1.2.5     zip_2.0.4 

```

**Comment by alexmosc** [comment] 2022-05-30 11:05
Update.

As a matter of fact the breaking of a document with such a hyperlink occurs at the `officer::read_docx(...)`. How I tested. If this function is called, and on the document I delete the part of a body with the problematic hyperlink, or even if I delete everything, then saving and opening also results in this error. So, some problem happens with the XML while opening a doc.

**Comment by davidgohel** [comment] 2022-05-30 11:26
Duplicate of #417

You are using a two-year-old version, since there have been more than 10 new versions. However, I don't know if it will fix your issue. We know we need to preserve URL and not encode them. This is the work that will be done to close #417.

**Closed by davidgohel** 2022-05-30 11:26 UTC

**Comment by alexmosc** [comment] 2022-05-30 13:02
> Duplicate of #417
> 
> You are using a two-year-old version, since there have been more than 10 new versions. However, I don't know if it will fix your issue. We know we need to preserve URL and not encode them. This is the work that will be done to close #417.

@davidgohel , you helped me, I am very thankful to you. My bad... I didn't try to update the package first of all. officer_0.4.2 does not reproduce the problem I mentioned on every case that I have had. Thank you again!
