### ISSUE TITLE
Paragraphs have white background

### ISSUE THREAD

**Issue by muranyia** [davidgohel/officer#20] opened 2017-05-24 20:18 UTC
It seems that a paragraph added with body_add_par() or body_add_fpar() has a white background, which effectively covers any background image in the page. A transparent default background would be more useful.

**Comment by davidgohel** [comment] 2017-05-25 06:48
That's already the case. Maybe I didn't understand your issue? Help me to reproduce...

[coco.docx](https://github.com/davidgohel/officer/files/1028189/coco.docx)



```
library(officer)
library(magrittr)
xx <- read_docx("coco.docx") %>% 
  body_add_par("A title", style = "heading 1") %>%
  body_add_par("Hello world!", style = "Normal") 

print(xx, target = "body_add_par.docx" )
```

**Comment by muranyia** [comment] 2017-05-25 12:21
Thanks for the test case. It helped me to find out that my problem is due to a bug in Word handling EMF images: when you insert the image it's OK, but after saving and reopening gradients are lost.

The only thing I'm still having difficulty with is to add a ggplot with transparent background into the document. The plot itself has transparent background, but not when inserted. With ggsave(), an additional bg="transparent" parameter is necessary which is passed to the graphics device.

**Comment by davidgohel** [comment] 2017-05-26 08:07
Sorry, can't reproduce, when using `body_add_img` with an image with transparency background, all is as expected.

**Comment by muranyia** [comment] 2017-05-26 11:17
I mean `body_add_gg()` and `body_add_vg()`.

**Comment by davidgohel** [comment] 2017-05-26 11:34
I will add a `...` argument to `body_add_gg` so that you can add parameters to png. For `body_add_vg`, it's already there (read about the `...` argument of `body_add_vg`).

**Comment by davidgohel** [comment] 2017-05-26 11:42
I am closing this issue as it no more related to original question.

**Comment by davidgohel** [comment] 2017-05-26 11:42
I have added `...` to `body_add_gg`

**Closed by davidgohel** 2017-05-26 11:42 UTC

**Comment by muranyia** [comment] 2017-05-26 14:22
Thank you! It works.
