### ISSUE TITLE
layout_properties returns nothing with version 0.2.2

### ISSUE THREAD

**Issue by hewag1975** [davidgohel/officer#127] opened 2018-04-23 10:12 UTC
Hi David,

thanks for your package, I´ve been using it extensively throughout the last weeks.

When upgrading from 0.2.1 to 0.2.2 I experienced issues with one of the pptx-templates I was using so far (apologies for it being in German) when applying layout_properties as it returns nothing:
```
> ppt_notworks <- read_pptx(path = "sample_notworks.pptx")
> layout_summary(ppt_notworks)
layout      master
1         Deckblatt Master_2017
2      Agenda Opt.1 Master_2017
3     Level 1 Chart Master_2017
4   1_Level 1 Chart Master_2017
5   Detailchart GfK Master_2017
6 2_Detailchart GfK Master_2017
7 3_Detailchart GfK Master_2017
8 4_Detailchart GfK Master_2017
9  Transition Opt.1 Master_2017
> layout_properties(ppt_notworks, layout = "Deckblatt", master = "CM Master 2017")
[1] master_name name        type        id          ph_label    offx        offy        cx          cy         
<0 Zeilen> (oder row.names mit Länge 0)
```

However, using a blank pptx works as I´d expect:
```
> pptx_works <- read_pptx(path = "sample_works.pptx")
> layout_summary(pptx_works)
layout master
1                 Titelfolie Office
2  Titel und vertikaler Text Office
3  Vertikaler Titel und Text Office
4           Titel und Inhalt Office
5   Abschnitts-\nüberschrift Office
6               Zwei Inhalte Office
7                  Vergleich Office
8                  Nur Titel Office
9                       Leer Office
10    Inhalt mit Überschrift Office
11      Bild mit Überschrift Office
> layout_properties(pptx_works, layout = "Titelfolie", master = "Office")
   master_name       name     type id                   ph_label      offx     offy   cx        cy
17      Office Titelfolie       dt  4        Datumsplatzhalter 3 0.9166667 6.951389  3.0 0.3993056
28      Office Titelfolie      ftr  5     Fußzeilenplatzhalter 4 4.4166667 6.951389  4.5 0.3993056
45      Office Titelfolie   sldNum  6 Foliennummernplatzhalter 5 9.4166667 6.951389  3.0 0.3993056
56      Office Titelfolie ctrTitle  2                    Titel 1 1.6666667 1.227431 10.0 2.6111111
57      Office Titelfolie subTitle  3               Untertitel 2 1.6666667 3.939237 10.0 1.8107633
```

I´ve attached both templates for reproducibility:
[sample_works.pptx](https://github.com/davidgohel/officer/files/1937630/sample_works.pptx)
[sample_notworks.pptx](https://github.com/davidgohel/officer/files/1937631/sample_notworks.pptx)

Even though I do not know if this is really an issue with the package, I do not know where to place this problem. Do you have any idea?

Thanks for any support.
Hendrik

Here is my session:
```
> sessionInfo()
R version 3.4.4 (2018-03-15)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                   
[5] LC_TIME=German_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] officer_0.2.2

loaded via a namespace (and not attached):
 [1] compiler_3.4.4    R6_2.2.2          magrittr_1.5      htmltools_0.3.6   tools_3.4.4       base64enc_0.1-3   yaml_2.1.18       Rcpp_0.12.16     
 [9] uuid_0.1-2        xml2_1.2.0        R.methodsS3_1.7.1 digest_0.6.15     zip_1.0.0         R.utils_2.6.0     R.oo_1.21.0
```

**Comment by davidgohel** [comment] 2018-04-24 15:58
Hi

No problem, it was an bug in `officer`.

The issue is fixed now (on github). This happened because the master layout of `sample_notworks.pptx` is empty and the case was not managed :/

**Closed** 2018-04-24 15:59 UTC
Labels: bug
